name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Intentionally fail
        run: |
          echo "About to fail on purpose"
          exit 1
